version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 28000:27017
  app:
    image: app:1.0.0
    container_name: app
    ports:
      - 8081:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"